# sweep id joveemy7
program: fenchel_CIFAR_main.py
method: bayes
metric:
  name: total_weight_variance
  goal: minimize
parameters:
  softmax_temp:
    values: [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]