exp_title: original_config
dataset_name: cifar10
classification_model: Resnet34
influence_model: Net_IF
max_epoch: 100
influence_lr: 0.001
classification_lr: 0.001
batch_size: 64
classification_momentum: 0.9
classification_weight_decay: 0.01
influence_weight_decay: 1
influence_weight_init: 0.
softmax_temp: 1
test_id_num: 0
train_classification_till_converge: True
seed: 1
_gpu_id: 1
_ckpt_dir: checkpoints/fenchel/
_num_class: 10
_ckpt_name: last
