exp_title: original_config
dataset_name: cifar10
train_classes: ["airplane", "automobile", "bird", "cat", "deer", "dog", "frog", "horse", "ship", "truck"]
num_per_class: [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]
classification_model: Resnet34
influence_model: Net_IF
max_epoch: 100
influence_lr: 0.1
influence_momentum: 0.9
influence_weight_init: 0.
influence_weight_decay: 0.01
classification_lr: 0.001
classification_momentum: 0.9
classification_weight_decay: 0.01
dataWeight_weight_decay: 1
dataWeight_weight_init: 0.
batch_size: 32
softmax_temp: 10
test_id_num: 2
train_classification_till_converge: False
use_pretrain_classification: True
reset_pretrain_classification_every_epoch: True
seed: 1
_gpu_id: 2
_ckpt_dir: checkpoints/fenchel/
_num_class: 10
_ckpt_name: last
_pretrain_ckpt_name: single_test_seed_1_first1000_shuffled.pt
