dataset_name: GMM1D
classification_model: LogisticRegression
influence_model: GMM1D_IF
max_epoch: 100
influence_lr: 0.001
classification_lr: 0.001
ckpt_name: last
num_workers: 2
batch_size: 64
classification_momentum: 0.9
classification_weight_decay: 0.01
influence_weight_decay: 10.
influence_weight_init: 0.
softmax_temp: 1
test_id_num: 0
seed: 1
_gpu_id: 1
_ckpt_dir: checkpoints/fenchel/
