#9njhf77k
program: fenchel_CIFAR_main.py
method: bayes
metric:
  name: total_weight_variance
  goal: minimize
parameters:
  # max_epoch:
  #   values: [50]
  influence_lr:
    values: [0.01, 0.005, 0.001]
  classification_lr: 
    values: [0.01, 0.005, 0.001]
  batch_size:
    values: [64]
  classification_momentum:
    values: [0.9]
  classification_weight_decay:
    values: [0.01]
  influence_weight_decay:
    values: [1]
  softmax_temp:
    values: [1.0]
  max_epoch:
    values: [100]