# wandb agent influence_function/IF_PROJECT_single_test/vm6kf8ej
program: fenchel_image_main.py
method: bayes
project: IF_PROJECT_single_test
entity: influence_function
metric:
  goal: maximize
  name: correlation_ours
parameters:
  classification_model:
    value: MNIST_1
  optimizer_classification:
    values: ["SGD", "Adam"]
  classification_lr:
    values: [0.001]
  batch_size:
    values: [64]
  optimizer_influence:
    values: ["SGD", "Adam"]
  influence_lr:
    values: [0.001, 0.01]
  softmax_temp:
    values: [10]
  max_pretrain_epoch:
    values: [10]